main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('story1/', views.story1, name='story1'),
    path('isidata/', views.isidata, name='isidata'),
    path('savename/', views.savename, name = 'savename'),
    path('isidata/daftarkelas', views.daftarkelas, name = 'daftarkelas'),
    path('delete/<int:pk>', views.delete, name = 'delete'),
    path('details/<int:pk>', views.details, name = 'details'),
    path('activity/', views.activity, name = 'activity'),
    path('register/<int:pk>', views.register, name='register'),
    path('accordion/', views.accordion, name='accordion'),
    path('bookfinder/', views.bookfinder, name = 'bookfinder'),
    path('bookfinder/json/<str:searchKey>', views.json_response, name='json-story8-search'),
    path('user/', views.index9, name='landing'),
    path('user/login/', views.login9, name='login'),
    path('user/logout/', views.logout9, name='logout'),
    path('user/signup/', views.signup9, name='signup'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
]

main/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

class Activity(models.Model):

    class Meta:
        verbose_name_plural = 'Activities'
    name = models.CharField(max_length=50)

class Course(models.Model):
	mata_kuliah = models.CharField(max_length=30)
	dosen = models.CharField(max_length=17)
	sks = models.CharField(max_length=3, default='none')
	deskripsi = models.CharField(max_length=140, default='none')
	semester_tahun = models.CharField(max_length=20, default='none')
	ruang_kelas = models.CharField(max_length=30, default='none')


class Person(models.Model):

    name = models.CharField(max_length=50)

    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)

main/forms.py
from django import forms
from .models import Course

class Input_Form(forms.ModelForm):
	class Meta:
		model = Course
		fields = ['mata_kuliah', 'dosen', 'sks', 'deskripsi', 'semester_tahun', 'ruang_kelas']


	error_messages = {
		'required' : 'Please Type'
	}

	matkul_attrs = {
		'type' : 'text',
		'placeholder' : 'Mata Kuliah'
	}

	dosen_attrs = {
		'type' : 'text',
		'placeholder' : 'Dosen'
	}

	sks_attrs = {
		'type' : 'text',
		'placeholder' : 'SKS'
	}

	deskripsi_attrs = {
		'type' : 'text',
		'placeholder' : 'Deskripsi'
	}

	semester_attrs = {
		'type' : 'text',
		'placeholder' : 'Semester'
	}

	kelas_attrs = {
		'type' : 'text',
		'placeholder' : 'No. Ruang Kelas'
	}


	mata_kuliah = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=matkul_attrs))
	dosen = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=dosen_attrs))
	sks = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=sks_attrs))
	deskripsi = forms.CharField(label='', required=True, max_length=255, widget=forms.Textarea(attrs=deskripsi_attrs))
	semester_tahun = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=semester_attrs))
	ruang_kelas = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=kelas_attrs))

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, JsonResponse
from .forms import Input_Form
from .models import Course, Activity, Person
from django.urls import reverse 
from django.forms import inlineformset_factory, modelformset_factory
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
import requests

response = {}

def home(request):
    return render(request, 'homepage.html')

def about(request):
    return render(request, 'about.html')

def story1(request):
    return render(request, 'story1.html')

def isidata(request):
    response = {'input_form': Input_Form}
    return render(request, 'form.html', response)

def savename(request):
    form = Input_Form(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save() 
        return HttpResponseRedirect('/isidata/daftarkelas')
    else:
        return HttpResponseRedirect('/isidata/daftarkelas')

def daftarkelas(request):
	courses = Course.objects.all()
	response['courses'] = courses
	return render(request, 'results.html', response)

def delete(request, pk):
    kelas = Course.objects.filter(pk=pk)
    kelas.delete()    
    return HttpResponseRedirect('/isidata/daftarkelas')

def details(request, pk):
    kelas = Course.objects.get(pk=pk)
    response = {'kelas': kelas}
    return render(request, 'details.html', response)

def activity(request):
    activity_1 = Person.objects.filter(activity__name="Among Us")
    activity_2 = Person.objects.filter(activity__name="FIFA20")
    activity_3 = Person.objects.filter(activity__name="Nonton Film")
    response = {'activity_1': activity_1, 'activity_2': activity_2, 'activity_3': activity_3,}
    return render(request, 'activity.html', response)

def register(request, pk):
    PersonFormSet = inlineformset_factory(Activity, Person, fields=('name',))
    activity = Activity.objects.get(id=pk)
    formset = PersonFormSet(instance=activity)
    if request.method == "POST":
        formset = PersonFormSet(request.POST, instance=activity)
        if formset.is_valid():
            formset.save()
            return HttpResponseRedirect('/activity/')
    return render(request, 'register.html', {'formset': formset})

def accordion(request):
    return render(request, 'accordion.html')

def bookfinder(request):
    response = {
        
    }
    return render(request, 'bookfinder.html', response)


def json_response(request, **kwargs):
    resp = requests.get("https://www.googleapis.com/books/v1/volumes?q=" + kwargs["searchKey"])

    bookjson = resp.json()

    response = {
        "daftarBuku": [],
    }
    bookjson = bookjson["items"]
    
    for dataBuku in bookjson:
        buku = dataBuku["volumeInfo"]
        jsonBuku = {}


        jsonBuku["foto"] = buku["imageLinks"]["thumbnail"] if "imageLinks" in buku.keys() else "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/No_image_available_400_x_600.svg/600px-No_image_available_400_x_600.svg.png"
        jsonBuku["judul"] = buku["title"] if "title" in buku.keys() else "Title Not Found"
        jsonBuku["deskripsi"] = buku["description"] if "description" in buku.keys() else "Description Not Found"

        response["daftarBuku"].append(jsonBuku)

    respon = JsonResponse(response)

    return respon

def index9(request):
    return render(request,'user.html')

def login9(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        print("{}: {} ".format(username,password))
        if not username or not password:
            messages.error(request, "Please enter username / password correctly")
            return HttpResponseRedirect('/user/login')

        user = authenticate(request,username = username,password = password)
        if user is not None:
            login(request,user)
            return HttpResponseRedirect('/user/')
        else:
            messages.error(request, "Wrong credentials (Wrong Username / Password)")
            return HttpResponseRedirect('/user/login')
    else:
        return render(request,'login.html')

def logout9(request):
    logout(request)
    messages.success(request, "Successfully logged out.")
    return HttpResponseRedirect('/user/')

def signup9(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if not username or not password:
            messages.error(request, "Please enter username / password correctly")
            return HttpResponseRedirect('/user/signup')
        if User.objects.filter(username__iexact = username).exists():
            messages.error(request, "Username taken")
            return HttpResponseRedirect('/user/signup')
        else:
            user = User.objects.create_user(username=username, password=password)
            user.save()
            return HttpResponseRedirect('/user/login') #test for commit 1
    else:
        return render(request,'signup.html')

main/templates/about.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block content %}
    <head>
        <title>About Me</title>
    </head>
    <body>
        <div class = "layout">
            <div>
                <div class="big-text">About Me</div>
                <p class="aboutme-text">Nama Lengkap saya adalah Affan Mirza Chairy, biasa dipanggil teman-teman saya Affan. Saya lahir di Medan
                pada tanggal 16 April 2001. Saya besar di Jakarta selama 3 tahun dan di Depok selama 16 tahun. Saya mempunyai 
                satu kakak perempuan bernama Azra. Ia dua tahun lebih tua diatas saya.
                <br>
                Saya mempunyai beragam teman. Salah satunya adalah teman-teman SMA saya dahulu. Kami selalu 
                belajar dan bermain bersama. Pada akhirnya, kami semua diterima di perguruan tinggi yang diinginkan. 
                Berikut adalah biografi singkat saya.</p>
            </div>
            <div class="foto1"></div>
            <div class="foto2"></div>
            <div class="foto3"></div>
        </div>
    </body>
    {% endblock content %}
</html>

main/templates/accordion.html
{% extends "base.html" %}

{% block meta %}
{% endblock meta %}

{% block content %}
<title>Accordion</title>
{% load static %}
<link rel="stylesheet" href="{% static 'css/activity.css' %}">
<div class="wrapper col-12">
    <div class="d-flex flex-column justify-content-start align-items-center py-5 col-lg-8 mx-auto">
        <h1 >Hi, I am <b>Affan Mirza</b> !</h1>
        <div class="accordion col-md-10 p-0 mt-2 accordion-1" id="accor1">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Introduction</h2>
                <div class="buttons d-flex justify-content-end justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0">
                    <p>Greetings! My name is Affan</p>
                    <p>I am an undergraduate Information Systems student @ University of Indonesia</p>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-2" id="accor2">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Current Activities</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0">
                    <p>My current activities include:</p>
                    <ul class="m-0">
                        <li>Building knowledges of entrepreneurship</li>
                        <li>Learning investments</li>
                        <li>Reading self-motivation books</li>
                        <li>All things PROGRAMMING!</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-3" id="accor3">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Experiences</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0">
                    <p>Here are my current experiences:</p>
                    <ul class="m-0">
                        <li>Staff of Research and Strategic Action Department at BEM Fakultas Ilmu Komputer Universitas Indonesia</li>
                        <li>Staff of FUKI Corp.</li>
                        <li>Student Mentor at OKK UI</li>
                        <li>Staff of Relations and Publications at OH Fasilkom UI 2019</li>
                        <li>Staff of Equipment at PERAK 2020</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-4" id="accor4">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Achievements</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0">
                    <p>I don't really have significant ones, but here it is!</p>
                    <ul class="m-0">
                        <li>Accepted at CSUI</li>
                        <li>(Other upcoming achievements are on progress...)</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="accordion col-md-10 p-0 mt-2 accordion-5" id="accor5">
            <div class="header d-flex justify-content-between align-items-center">
                <h2 class="pl-4 py-2 title col-9 mb-0">Contact</h2>
                <div class="buttons d-flex justify-content-end col-3 p-0">
                    <div class="up p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&uarr;</h2>
                    </div>
                    <div class="down p-2 d-flex align-items-center justify-content-center col-6">
                        <h2>&darr;</h2>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="px-4 py-3 m-0 d-flex flex-column">
                    <div class="d-flex mt-2">
                        <img src="https://www.stickpng.com/assets/images/58e91afdeb97430e81906504.png" height="30"
                            width="30" class="mr-2">
                        <h4><a href="https://www.linkedin.com/in/affan-mirza-chairy/">LinkedIn</a></h4>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<script src="{% static 'js/accordion.js' %}"></script>
{% endblock %}

main/templates/activity.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
{% block content %}
<link rel="stylesheet" href="{% static 'css/activity.css' %}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Activity</title>
</head>
<body>
    <div class="container-fluid">
        <div class="header">
            <h1 class="text-center" style="color: #63526C;">My Activity</h1>
        </div>
        <div class="row">
            <div class="column text-center">
                <h3>Among Us</h3>
                <img src="{% static 'img/amongus.png' %}" style="width:100%">
                <a class="btn btn-dark mr-2 mt-2 mb-5" href="/register/1">Register</a>
                <table class="table">
                    <thead class="thead-dark">
                        <th scope="col">Nama Teman</th>
                    </thead>
                    <tbody>
                        {% for i in activity_1 %}
                        <tr>
                            <td class="table-dark">{{ i.name }} </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="column text-center">
                <h3>FIFA 20</h3>
                <img src="{% static 'img/fifa20.png' %}" width="1024" height="500" style="width:100%">
                <a class="btn btn-dark mr-2 mt-2 mb-5" href="/register/2">Register</a>
                <table class="table">
                    <thead class="thead-dark">
                        <th scope="col">Nama Teman</th>
                    </thead>
                    <tbody>
                        {% for i in activity_2 %}
                        <tr>
                            <td class="table-dark">{{ i.name }} </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="column text-center">
                <h3>Nonton Film</h3>
                <img src="{% static 'img/watchfilms.jpg' %}" style="width:100%">
                <a class="btn btn-dark mr-2 mt-2 mb-5" href="/register/3">Register</a>
                <table class="table">
                    <thead class="thead-dark">
                        <th scope="col">Nama Teman</th>
                    </thead>
                    <tbody>
                        {% for i in activity_3 %}
                        <tr>
                            <td class="table-dark">{{ i.name }} </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
</body>
{% endblock content %}
</html>

main/templates/bookfinder.html
{% extends "base.html"%}
{% load static %}

<link rel="stylesheet" href="{% static 'css/activity.css' %}">

{% block content %}
<title>Find Book</title>
<div class="d-flex align-items-center">
    <div class="container text-center">
      <h1 class="display-4" style="font-family: Playfair Display; color:rgba(138,43,226,1)">Find Any Book!</h1>
    </div>
</div>
<div class="container">
    <div class="my-searchbox">
        <div class="mb-4">
            <input id="search" class="form-control" type="text" placeholder="Search" aria-label="Search">
        </div>
    </div>
    <div class="my-booktable">
        <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">No.</th>
                <th scope="col">Foto</th>
                <th scope="col">Judul</th>
                <th scope="col">Deskripsi</th>
              </tr>
            </thead>
            <tbody class="my-tablebody" style="font-family: Playfair Display;">
            </tbody>
    </div>
</div>

<script src="{% static 'js/bookfinder.js' %}"></script>
{% endblock %}

main/templates/details.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block content %}
    <head>
        <style>
            table {
              font-family: arial, sans-serif;
              border-collapse: collapse;
              width: 100%;
            }
            
            td, th {
              border: 1px solid #dddddd;
              text-align: left;
              padding: 8px;
            }
            
            tr:nth-child(even) {
              background-color: #dddddd;
            }
            </style>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body style="text-align: center;">
        <br>
        {% if kelas %}
        <table>
            <tr>
                <th>Nama Kelas</th>
                <th>Dosen</th>
                <th>Jumlah SKS</th>
                <th>Deskripsi</th>
                <th>Semester</th>
                <th>Ruang</th>
            </tr>
            <tr>
                <td>{{ kelas.mata_kuliah}}</td>
                <td>{{ kelas.dosen }}</td>
                <td>{{ kelas.sks }}</td>
                <td>{{ kelas.deskripsi }}</td>
                <td>{{ kelas.semester_tahun }}</td>
                <td>{{ kelas.ruang_kelas }}</td>
            </tr>

        </table>
        {% endif %}
    </body>
{% endblock content %}
</html>

main/templates/form.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block content %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Isi Form</title>
    </head>
    <body style="text-align: center;">
        <h2>Isi Mata Kuliah Disini!</h2>
        <form action = "{% url 'main:savename' %}" method="POST">
            {% csrf_token %}
            {{ input_form.as_p }}
            <input type="submit" value="Submit">
        </form>
    </body>
{% endblock content %}
</html>

main/templates/homepage.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% block content %}
    <head>
        <title>Affanmrz</title>
    </head>
    <body>
        <div class = "layout">
            <div class = "banner-text" >Hi there. I’m 
                <div style="color:  rgba(138,43,226,1)">
                    Affan.
                </div>
                A Computer Science Student and a Data Enthusiast.
            </div>
            <div class = "profile-pic"></div>
            <div class = "about-btn-2">
                <a style= "text-decoration: none; color:rgba(50,205,50,1)" href="/about">Get to know me!</a>
            </div>
            <div class = "experience-btn-2">Experiences</div>
        </div>
    </body>
    {% endblock content %}
</html>

main/templates/login.html
{% extends 'base.html' %}

{% block title %}Story10 - Login Page{% endblock %}

{% block content %}
    <div class="container">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <script>
                alert("{{ message }}")
            </script>
            {% endfor %}
        </ul>
        {% endif %}
  
        {% if user.is_authenticated %}
            <h1>Selamat Datang {{ user.username }} !!</h1>
                <a class="btn btn-primary" href="{% url 'main:logout' %}">Logout</a>
        {% else %}
        <h1>Log In</h1>
        <p>Don't have an account? You can create it  <a href="{% url 'main:signup' %}">here</a></p>
        <form  action="{% url 'main:login' %}" method="POST">
            {% csrf_token %}
                <label for="#username">Username</label>
                <input id="username" name="username" class="form-control" type="text">
                <label for="#password">Password</label>
                <input id="password" name="password" class="form-control" type="password">
                <br>
                <input id="sub-login" class="btn btn-primary" type="submit" value="Log In">
            </form>
        {% endif %}
    </div>
{% endblock %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

main/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
<html lang="en">
{% block content %}
<link rel="stylesheet" href="{% static 'css/activity.css' %}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>
    <div class="container-fluid">
        <form action="" class="main-form" id="form" method="POST">
            <h1>Register Forms</h1>
            {% csrf_token %}
            <div class="row">
                <div class="col md-4">
                    <div class="form-group">
                        {{ formset.management_form }}
                        {% for form in formset %}
                        {{ form|crispy }}
                        {% endfor %}
                        <br>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-dark">Submit</button>
        </form>
    </div>    
</body>
{% endblock content %}
</html>

main/templates/results.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block content %}
    <head>
        <style>
            table {
              font-family: arial, sans-serif;
              border-collapse: collapse;
              width: 100%;
            }
            
            td, th {
              border: 1px solid #dddddd;
              text-align: left;
              padding: 8px;
            }
            
            tr:nth-child(even) {
              background-color: #dddddd;
            }
            </style>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Daftar Kelas</title>
    </head>
    <body style="text-align: center;">
        <h2>Daftar Kelas-kelas:</h2>
        {% if courses %}
            <table>
                <tr>
                    <th>Nama Kelas</th>
                    <th>Detil</th>
                    <th>Hapus</th>
                </tr>
            {% for course in courses %}
                <tr>
                    <td>{{ course.mata_kuliah }}</td>
                    <td><a href="{% url 'main:details' pk=course.pk %}">Details</a></td>
                    <td> <a href="{% url 'main:delete' pk=course.pk %}">Delete</a></td>
                    {% csrf_token %}
                </tr>
            <br/>
            {% endfor %}
        </table>
    {% endif %}
    </body>
    {% endblock content %}
</html>

main/templates/signup.html
{% extends 'base.html' %}

{% block title %}Story10 - Signup Page{% endblock %}

{% block content %}
    <div class="container">
        
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <script>
                alert("{{ message }}")
            </script>
            {% endfor %}
        </ul>
        {% endif %}
  
        {% if user.is_authenticated %}
            <h1>Logged as {{ user.username }}</h1>
                <a class="btn btn-primary" href="{% url 'main:logout' %}">Logout</a>
                {% else %}
                    <h1>Sign Up</h1>
                    <p>Have an account? You can log in <a href="{% url 'main:login' %}">here</a></p>
                    <form  action="{% url 'main:signup' %}" method="POST">
                        {% csrf_token %}
                        <label for="#username">Username</label>
                        <input id="username" name="username" class="form-control" type="text">
                        <label for="#password">Password</label>
                        <input id="password" name="password" class="form-control" type="password">
                        <br>
                        <input id="sub-signup" class="btn btn-primary" type="submit" value="Sign me up!">
                    </form>
        {% endif %}
    </div>
{% endblock %}

main/templates/story1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    <h1>Hi All!</h1>
    <img alt="pp" src= "https://i.imgur.com/wga6RUs.jpg"
    width="200" height="200">
    <p>Nama saya Affan Mirza Chairy</p>
    <p>NPM saya adalah 1906302516</p>
    <p>Angkatan di Fasilkom 2019 (Maung!)</p>
    <p>Berkuliah di Universitas Indonesia</p>
</head>
<body>
    <style>
        table, th, td {border: 1px solid black;}
    </style>
    <h2>About me:</h2>
    <p>Di waktu luang, saya seringkali bermain game atau membaca artikel. Tapi tidur tetap kesukaan saya</p>
    <p>Hobi saya adalah:</p>
    <ul>
        <li>Main Bulutangkis</li>
        <li>Main bola</li>
    </ul>
    <table style = "width:30%">
        <tr>
            <th>Riwayat Pendidikan</th>
            <th>Tempat</th>
        </tr>
        <tr>
            <td>SMP</td>
            <td>SMP Negeri 3 Depok</td>
        </tr>
        <tr>
            <td>SMA</td>
            <td>SMA Negeri 2 Depok</td>
        </tr>
        <tr>
            <td>Perguruan Tinggi</td>
            <td>Fasilkom UI</td>
        </tr>
    </table>

    <p>Visit my social medias at:</p>
    <a href="https://www.instagram.com/affanmrz/">
        <img alt="IG" src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Instagram_logo_2016.svg/600px-Instagram_logo_2016.svg.png"
        width="40" height="40">
     </a>
     <a href="https://www.twitter.com/affanmrz/">
        <img alt="Twitter" src="https://i.pinimg.com/originals/28/90/ba/2890bac9ba41e52707f36268231dfe9e.png"
        width="40" height="40">
     </a>
     <a href="https://www.linkedin.com/in/affan-mirza-chairy/">
        <img alt="LinkedIn" src="https://www.iconfinder.com/data/icons/social-messaging-ui-color-shapes-2-free/128/social-linkedin-circle-512.png"
        width="40" height="40">
     </a>

</body>
</html>

main/templates/user.html
{% extends 'base.html' %}

{% block title %}Story10{% endblock %}

{% block content %}
<div style="margin-top: 1em;" class="container"></div>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <script>
            alert("{{ message }}")
        </script>
        {% endfor %}
    </ul>
    {% endif %}

    {% if user.is_authenticated %}
    <div class="d-flex align-items-center">
      <div class="container text-center">
        <h3>Selamat Datang {{ user.username }} !!</h3>
        <br>
        <br>    
        <a id='sub-logout' class="btn btn-primary" href="{% url 'main:logout' %}">Logout</a>
      </div>
    </div>
      {% else %}
      <div class="d-flex align-items-center">
        <div class="container text-center">
        <h1 class="display-4" style="font-family: Montserrat; color:rgba(138,43,226,1)">You are not logged in.</h1>
        <br>
        <h3 style="color: rgba(50,205,50,1); font-family: Montserrat">Signup/Login is Required</h3>
        <a id='login' class="btn btn-success" href="{% url 'main:login' %}">Log in</a>
        <a id='signup' class="btn btn-outline-success" href="{% url 'main:signup' %}">Sign up</a>
      </div>
      </div>
      {% endif %}
</div>
{% endblock %}